---
title: "Untitled"
author: "Nate Thomas"
date: "8/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RMySQL)
library(ggplot2)
library(dplyr)
library(maps)
library(viridis)
library(plotly)
theme_set(
  theme_void()
  )
```

```{r}
getSqlConnection <- function(){
  con <-
    dbConnect(
      RMySQL::MySQL(),
      username = 'default',
      password = 'sqDlsPOubh89zrgy',
      host = 'localhost',
      db = 'project',
      port = 3306
    ) # TODO: use a configuration group `group = "my-db")`
  return(con)
}
conn <- getSqlConnection()
res <- dbListTables(conn)
res
```

```{r}
po_loc <- dbGetQuery(conn, "select orders.ship_state_province,
                	count(orders.id) as 'po_counts'
                	from orders 
                  inner join customers
                  on orders.customer_id = customers.id
                  group by orders.ship_state_province
                  order by po_counts desc;")
po_loc
```

# 1
```{r}
states_map <- map_data("state")
po_loc$region <- tolower(state.name[match(po_loc$ship_state_province,state.abb)])
df<- merge(states_map, po_loc, by = c("region"), all=TRUE)

df <- left_join(states_map,df,by = c("region"))

<<<<<<< HEAD
map <- ggplot(df, aes(long.x, lat.x, group = group.x))+
=======
map <- ggplot(df, aes(long.x, lat.x, group = group.x, labels=region))+
>>>>>>> e2029a42d245944d0d5fcc9384f8fd88a46432f3
  geom_polygon(aes(fill = po_counts), color = "white")+
  scale_fill_viridis_c(option = "C")

ggplotly(map)
```
#2
```{r}
POs_for_restocking <- dbGetQuery(conn, "SELECT COUNT(based_on_CO) total_PO, SUM(based_on_CO) AS total_based_on_customer_orders, SUM(based_on_CO)/COUNT(based_on_CO) AS perc_based_on_customer_orders FROM
(SELECT *, (purchase_orders.notes IS NOT NULL) AS based_on_CO 
FROM  `purchase_orders`) as tmp1;
")
POs_for_restocking
po = POs_for_restocking$total_based_on_customer_orders
cd
```

```{r}
ggplot(POs_for_restocking, aes=(y=perc_based_on_customer_orders,x=''))

ggplotly(rev)
ggplotly(perc_margin)
```
#3
```{r}
categories_stcost <- dbGetQuery(conn, "
select category, avg(standard_cost) as avg_standard_cost
	from products 
	group by category
    order by avg_standard_cost desc;
")
categories_stcost
```
```{r}
p0 <- ggplot(categories_stcost, aes(x=category,y=avg_standard_cost))+
  geom_bar(position="stack", stat="identity")+
  geom_text(aes(y=5,label=round(avg_standard_cost)))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplotly(p0)
```


```{r}
cost_rev_table <- list()
cost_rev_table$by_product <- dbGetQuery(conn, "select *,margin/total_cost 
          as 'perc_margin' from (
          select product_id, product_name,round(sum(order_details.quantity*order_details.unit_price)) as 'total_rev',
          round(sum(order_details.quantity*products.standard_cost)) as 'total_cost',
          round(sum((order_details.quantity*order_details.unit_price-order_details.quantity*products.standard_cost)/order_details.quantity*order_details.unit_price)) as 'margin'
          from orders
          inner join order_details
          on orders.id = order_details.order_id
          inner join products
          on products.id = order_details.product_id
          group by product_id) as tmp 
          order by perc_margin desc;")


rev <- ggplot(cost_rev_table$by_product, aes(x=product_name,y=total_rev))+
  geom_bar(position="stack", stat="identity")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

perc_margin <- ggplot(cost_rev_table$by_product, aes(x=reorder(product_name,-perc_margin),y=perc_margin))+
  geom_bar(position="stack", stat="identity")+
  geom_text(aes(y=0.5,label=round(perc_margin,2), angle=90, lineheight=0.1))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
perc_margin
ggplotly(rev)
ggplotly(perc_margin)
```


```{r}
sc <- dbGetQuery(conn, 'select unit_cost, standard_cost, (unit_cost-standard_cost) as diff
	from purchase_order_details
    inner join products
    on products.id = purchase_order_details.product_id;')


sc
```
```{r}
save.image()
```
